# Use the official Node.js image as the base
FROM node:18.15-alpine

# Set the working directory in the container
WORKDIR /backend

# Copy the package.json and package-lock.json files
COPY package*.json ./

RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port on which your frontend will run (assuming it's 3000)
EXPOSE 3001

# Start the frontend server
CMD ["npm", "start"]